
insert into SCHOOL (SCHOOL_ID,SCHOOL_SCORE,PRINCIPAL_NAME,SCHOOL_NAME)

 values (1,1,'NUJUMA','BENTON VILLE PUBLICSCHOOL');
 
 
insert into SCHOOL (SCHOOL_ID,SCHOOL_SCORE,PRINCIPAL_NAME,SCHOOL_NAME)

 values (2,2,'parween','irvingE PUBLICSCHOOL');
 
 
 
